### PR TITLE
fix for upcoming ast change

### PR DESCRIPTION
**Pull request by krux02**
This PR should get you ready for the upcoming AST change: 
https://github.com/nim-lang/Nim/pull/13793
Sorry for you inconvencience. Since you are affected by this change, your opinion about this change is of interest.

### CODE REVIEW

**Comment by nigredo-tori** [comment]
@krux02, sorry, for some reason Travis checks don't get displayed in the PR UI. For now you can just go [here](https://travis-ci.com/github/nigredo-tori/classy/pull_requests) to see that your PR doesn't pass the tests. `nnkTupleConstr` doesn't exist in Nim 0.18 and older. Those Nim versions are ancient, but I'd rather not drop compatibility with them without a good reason. Could you please add a `when` to preserve the existing logic for old Nim versions?

Also, the tests (which you can run via `nim tests`) seem to fail with your Nim PR branch. I've minimized the issue and posted the test case there.

**Comment by krux02** [comment]
This should work now. I also fixed a warning.

**Comment by nigredo-tori** [comment]
This now works OK with the current version of https://github.com/nim-lang/Nim/pull/13793. I'm preemptively merging this PR, so that https://github.com/nim-lang/Nim/pull/13793 passes ecosystem build checks, but I reserve the right to roll it back if that PR doesn't get merged.

**Comment by nigredo-tori** [comment]
A little update here. The tests pass OK with Nim 1.4.4 and `devel`, so I've pushed the 0.0.4 release. I've poked around with the pure parts of [nimfp](https://github.com/vegansk/nimfp) in a separate branch, and those *should* work as well (I've only had to update the tests to match the changes in Nim itself). However, the concurrency stuff in nimfp needs some redesign after the latest changes in the Nim concurrency model. I never really got into that part of the library, I haven't been following Nim for two years now - and I don't have the energy to dive back into all of that. Sorry!

I've opened an [issue](https://github.com/vegansk/nimfp/issues/23) to update the code, but I don't think that will happen any time soon.

**Pull request merged**
